---
version: 2
plan:
  project-key: PT2
  key: ND
  name: 2nd
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  other:
    all-other-apps:
      custom.test.ephemeral.agent.enabled: 'false'
  tasks:
  - checkout:
      force-clean-build: false
      description: Checkout Default Repository
  artifact-subscriptions: []
repositories:
- pat-mak2:
    scope: global
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: PT-ND
plan-permissions:
- users:
  - admin
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
...
